/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CandlesRouteImport } from './routes/candles'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as CustomOrdersRouteImport } from './routes/custom-orders'
import { Route as JewelryRouteImport } from './routes/jewelry'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PensRouteImport } from './routes/pens'
import { Route as PhoneCasesRouteImport } from './routes/phone-cases'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TumblersRouteImport } from './routes/tumblers'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CandlesRoute = CandlesRouteImport.update({
  id: '/candles',
  path: '/candles',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrdersRoute = CustomOrdersRouteImport.update({
  id: '/custom-orders',
  path: '/custom-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelryRoute = JewelryRouteImport.update({
  id: '/jewelry',
  path: '/jewelry',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PensRoute = PensRouteImport.update({
  id: '/pens',
  path: '/pens',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneCasesRoute = PhoneCasesRouteImport.update({
  id: '/phone-cases',
  path: '/phone-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TumblersRoute = TumblersRouteImport.update({
  id: '/tumblers',
  path: '/tumblers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candles': typeof CandlesRoute
  '/checkout': typeof CheckoutRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/custom-orders': typeof CustomOrdersRoute
  '/jewelry': typeof JewelryRoute
  '/login': typeof LoginRoute
  '/pens': typeof PensRoute
  '/phone-cases': typeof PhoneCasesRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRouteWithChildren
  '/tumblers': typeof TumblersRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candles': typeof CandlesRoute
  '/checkout': typeof CheckoutRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/custom-orders': typeof CustomOrdersRoute
  '/jewelry': typeof JewelryRoute
  '/login': typeof LoginRoute
  '/pens': typeof PensRoute
  '/phone-cases': typeof PhoneCasesRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRouteWithChildren
  '/tumblers': typeof TumblersRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candles': typeof CandlesRoute
  '/checkout': typeof CheckoutRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/custom-orders': typeof CustomOrdersRoute
  '/jewelry': typeof JewelryRoute
  '/login': typeof LoginRoute
  '/pens': typeof PensRoute
  '/phone-cases': typeof PhoneCasesRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRouteWithChildren
  '/tumblers': typeof TumblersRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/candles'
    | '/checkout'
    | '/classes'
    | '/contact'
    | '/custom'
    | '/custom-orders'
    | '/jewelry'
    | '/login'
    | '/pens'
    | '/phone-cases'
    | '/shipping-returns'
    | '/shop'
    | '/tumblers'
    | '/shop/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/candles'
    | '/checkout'
    | '/classes'
    | '/contact'
    | '/custom'
    | '/custom-orders'
    | '/jewelry'
    | '/login'
    | '/pens'
    | '/phone-cases'
    | '/shipping-returns'
    | '/shop'
    | '/tumblers'
    | '/shop/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/candles'
    | '/checkout'
    | '/classes'
    | '/contact'
    | '/custom'
    | '/custom-orders'
    | '/jewelry'
    | '/login'
    | '/pens'
    | '/phone-cases'
    | '/shipping-returns'
    | '/shop'
    | '/tumblers'
    | '/shop/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CandlesRoute: typeof CandlesRoute
  CheckoutRoute: typeof CheckoutRoute
  ClassesRoute: typeof ClassesRoute
  ContactRoute: typeof ContactRoute
  CustomRoute: typeof CustomRoute
  CustomOrdersRoute: typeof CustomOrdersRoute
  JewelryRoute: typeof JewelryRoute
  LoginRoute: typeof LoginRoute
  PensRoute: typeof PensRoute
  PhoneCasesRoute: typeof PhoneCasesRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  ShopRoute: typeof ShopRouteWithChildren
  TumblersRoute: typeof TumblersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candles': {
      id: '/candles'
      path: '/candles'
      fullPath: '/candles'
      preLoaderRoute: typeof CandlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-orders': {
      id: '/custom-orders'
      path: '/custom-orders'
      fullPath: '/custom-orders'
      preLoaderRoute: typeof CustomOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewelry': {
      id: '/jewelry'
      path: '/jewelry'
      fullPath: '/jewelry'
      preLoaderRoute: typeof JewelryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pens': {
      id: '/pens'
      path: '/pens'
      fullPath: '/pens'
      preLoaderRoute: typeof PensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-cases': {
      id: '/phone-cases'
      path: '/phone-cases'
      fullPath: '/phone-cases'
      preLoaderRoute: typeof PhoneCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tumblers': {
      id: '/tumblers'
      path: '/tumblers'
      fullPath: '/tumblers'
      preLoaderRoute: typeof TumblersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CandlesRoute: CandlesRoute,
  CheckoutRoute: CheckoutRoute,
  ClassesRoute: ClassesRoute,
  ContactRoute: ContactRoute,
  CustomRoute: CustomRoute,
  CustomOrdersRoute: CustomOrdersRoute,
  JewelryRoute: JewelryRoute,
  LoginRoute: LoginRoute,
  PensRoute: PensRoute,
  PhoneCasesRoute: PhoneCasesRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  ShopRoute: ShopRouteWithChildren,
  TumblersRoute: TumblersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
